module.exports = {
    GOT_POSTS: 'GOT_POSTS',
    LOGIN: 'LOGIN',
    API_LOGIN: 'API_LOGIN',
    LOGGINED: 'LOGGINED',
    GET_USER: 'GET_USER',
    EDIT_POST: 'EDIT_POST',
    EDITED_POST: 'EDITED_POST',
    CREATE_POST: 'CREATE_POST',
    CREATED_POST: 'CREATED_POST'
};